[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-aedt-toolkits-antennas"
dynamic = ["version"]
description = "A python wrapper for ansys pyaedt-toolkits ansys.aedt.toolkits.antennas"
readme = "README.rst"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "build==0.8.0",
    "twine==4.0.1",
    "pyaedt==0.6.46",
    "importlib-metadata >=4.0",
]

[project.optional-dependencies]
tests = [
    "pytest==7.2.1",
    "pytest-cov==4.0.0",
]
doc = [
    "ansys-sphinx-theme==0.8.2",
    "numpydoc==1.5.0",
    "sphinx==5.3.0",
    "sphinx-copybutton==0.5.1",
    "enum-tools[sphinx]==0.9.0.post1",
]

[tool.flit.module]
name = "ansys.aedt.toolkits.antennas"

[project.urls]
Source = "https://github.com/pyansys/pyaedt-toolkits.git"
Tracker = "https://github.com/pyansys/pyaedt-toolkits.git/issues"
Homepage = "https://github.com/pyansys/pyaedt-toolkits.git"


[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["ansys.pyaedt_toolkits"]

[tool.coverage.report]
show_missing = true
