[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-aedt-toolkits-antenna"
dynamic = ["version"]
description = "Toolkit to design antennas with Ansys AEDT."
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.core@ansys.com"},
]
maintainers = [
    {name = "ANSYS, Inc.", email = "pyansys.core@ansys.com"},
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "build==1.0.3",
    "twine==4.0.2",
    "pyaedt",
    "importlib-metadata >=4.0",
    "PySide6-Essentials==6.6.0",
    "pyqtgraph",
    "pyvistaqt",
    "qdarkstyle",
    "flask",
]

[project.optional-dependencies]
tests = [
    "pytest==7.4.3",
    "pytest-cov==4.1.0",
]
doc = [
    "numpydoc==1.6.0",
    "ansys-sphinx-theme==0.12.4",
    "recommonmark==0.7.1",
    "sphinx==7.2.6",
    "sphinx-copybutton==0.5.2",
    "enum-tools[sphinx]==0.11.0",
    "sphinx-autoapi==3.0.0",
    "sphinx-autobuild==2021.3.14",
    "sphinx-autodoc-typehints==1.25.1",
    "sphinx-gallery==0.14.0",
    "sphinx-notfound-page==1.0.0",
    "nbsphinx==0.9.3",
]

[tool.flit.module]
name = "ansys.aedt.toolkits.antenna"

[project.urls]
Source = "https://github.com/ansys/pyaedt-toolkits-antenna"
Issues = "https://github.com/ansys/pyaedt-toolkits-antenna/issues"
Discussions = "https://github.com/ansys/pyaedt-toolkits-antenna/discussions"
Documentation = "https://aedt.antenna.toolkit.docs.pyansys.com"
Releases = "https://github.com/ansys/pyaedt-toolkits-antenna/releases"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 120
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["ansys.aedt"]

[tool.coverage.report]
show_missing = true
