Antenna_Name = "Axial_Mode"
Frequency = 10.0
Expected_Gain = 12.0
Feeder_Length = 10.0
Boundary_Condition = ["Radiation", "PML", "FEBI", "None"]
Origin_X_Position = 0.0
Origin_Y_Position = 0.0
Origin_Z_Position = 0.0
Coordinate_System = "Global"