Antenna_Name = "BowTie_Rounded"
Frequency = 10
Boundary_Condition = ["Radiation", "PML", "FEBI", "None"]
Origin_X_Position = 0.0
Origin_Y_Position = 0.0
Origin_Z_Position = 0.0
Coordinate_System = "Global"
