[defaults]
toolkit_name = "antenna"
log_file = "backend.log"
debug = true

[antenna]
antenna_type = ""
antenna_created = false
length_unit = "meter"
parameters = {}
parameters_hfss = {}
synth_only = false

[[antenna.synthesis]]
antenna_name = ""
coordinate_system = "Global"
frequency = 10.0
frequency_unit = "GHz"
feeder_length = 0.0
gain_value = 0.0
material = "pec"
material_properties = {}
origin = [0.0, 0.0, 0.0]
outer_boundary = ""
start_frequency = 0.0
stop_frequency = 0.0
substrate_height = 0.1

[[antenna.setup]]
component_3d = false
create_setup = false
lattice_pair = false
num_cores = 4
sweep = 20
