name: GitHub CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.9'
  DOCUMENTATION_CNAME: 'pyaedt_toolkits.docs.pyansys.com'
  LIBRARY_NAME: 'ansys-aedt-toolkits-antennas'
  LIBRARY_NAMESPACE: 'ansys.aedt.toolkits.antennas'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: "Code style"
    runs-on: [pyaedt-toolkit-1]
    steps:
      - uses: pyansys/actions/code-style@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false

  doc-style:
    name: "Documentation style"
    runs-on: ubuntu-latest
    steps:
      - uses: pyansys/actions/doc-style@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  smoke-tests:
    name: "Build and Smoke tests"
    runs-on: [pyaedt-toolkit-1]
    needs: [code-style]
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
    steps:
      - uses: pyansys/actions/build-wheelhouse@v2
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          library-namespace: ${{ env.LIBRARY_NAMESPACE }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  tests:
    name: "Tests"
    runs-on: [pyaedt-toolkit-1]
    needs: [smoke-tests]
    strategy:
      matrix:
       python-version: ['3.9']
      fail-fast: false
    steps:
      - uses: pyansys/actions/tests-pytest@v2
        with:
          pytest-extra-args: "--cov=ansys --cov-report=term --cov-report=html:.cov/html"

  doc-build:
    name: "Build documentation"
    runs-on: [pyaedt-toolkit-1]
    needs: [doc-style]
    steps:
      - uses: pyansys/actions/doc-build@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    runs-on: [pyaedt-toolkit-1]
    needs: [doc-build]
    if: github.event_name == 'push'
    steps:
      - uses: pyansys/actions/doc-deploy-dev@v2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: [pyaedt-toolkit-1]
    needs: [doc-deploy-dev]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    steps:
      - uses: pyansys/actions/doc-deploy-stable@v2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-library:
    name: "Build library basic example"
    runs-on: [pyaedt-toolkit-1]
    needs: [tests, doc-deploy-stable]
    steps:
      - uses: pyansys/actions/build-library@v2
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
